/*
UploadThing REST API

UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.

The version of the OpenAPI document: 6.4.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  CallbackApi,
  FileApi,
  MultipartApi,
  ServerCallbackApi,
  UploadApi,
  UsageInfoApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { UploadThingCustom } from "./client-custom";

export class UploadThing extends UploadThingCustom {
  readonly callback: CallbackApi;
  readonly file: FileApi;
  readonly multipart: MultipartApi;
  readonly serverCallback: ServerCallbackApi;
  readonly upload: UploadApi;
  readonly usageInfo: UsageInfoApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.callback = new CallbackApi(configuration);
    this.file = new FileApi(configuration);
    this.multipart = new MultipartApi(configuration);
    this.serverCallback = new ServerCallbackApi(configuration);
    this.upload = new UploadApi(configuration);
    this.usageInfo = new UsageInfoApi(configuration);
  }

}
