/* tslint:disable */
/* eslint-disable */
/*
UploadThing REST API

UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.

The version of the OpenAPI document: 6.4.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CallbackMarkUploadFailedRequest } from '../models';
// @ts-ignore
import { CallbackMarkUploadFailedResponse } from '../models';
// @ts-ignore
import { ErrBadRequest } from '../models';
// @ts-ignore
import { ErrInternalServerError } from '../models';
// @ts-ignore
import { ErrUnauthorized } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * CallbackApi - axios parameter creator
 * @export
 */
export const CallbackApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Mark an upload as failed, or abort a multipart upload. This will free up resources and revert the storage quota.
         * @param {string} xUploadthingVersion 
         * @param {string} [xUploadthingFePackage] 
         * @param {string} [xUploadthingBeAdapter] 
         * @param {CallbackMarkUploadFailedRequest} [callbackMarkUploadFailedRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        markUploadFailed: async (xUploadthingVersion: string, xUploadthingFePackage?: string, xUploadthingBeAdapter?: string, callbackMarkUploadFailedRequest?: CallbackMarkUploadFailedRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xUploadthingVersion' is not null or undefined
            assertParamExists('markUploadFailed', 'xUploadthingVersion', xUploadthingVersion)
            const localVarPath = `/failureCallback`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "x-uploadthing-api-key", keyParamName: "apiKeyAuth", configuration })
            if (xUploadthingVersion != null) {
                localVarHeaderParameter['x-uploadthing-version'] = String(xUploadthingVersion);
            }

            if (xUploadthingFePackage != null) {
                localVarHeaderParameter['x-uploadthing-fe-package'] = String(xUploadthingFePackage);
            }

            if (xUploadthingBeAdapter != null) {
                localVarHeaderParameter['x-uploadthing-be-adapter'] = String(xUploadthingBeAdapter);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: callbackMarkUploadFailedRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/failureCallback',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(callbackMarkUploadFailedRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CallbackApi - functional programming interface
 * @export
 */
export const CallbackApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CallbackApiAxiosParamCreator(configuration)
    return {
        /**
         * Mark an upload as failed, or abort a multipart upload. This will free up resources and revert the storage quota.
         * @param {CallbackApiMarkUploadFailedRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async markUploadFailed(requestParameters: CallbackApiMarkUploadFailedRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CallbackMarkUploadFailedResponse>> {
            const callbackMarkUploadFailedRequest: CallbackMarkUploadFailedRequest = {
                fileKey: requestParameters.fileKey,
                uploadId: requestParameters.uploadId
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.markUploadFailed(requestParameters.xUploadthingVersion, requestParameters.xUploadthingFePackage, requestParameters.xUploadthingBeAdapter, callbackMarkUploadFailedRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CallbackApi - factory interface
 * @export
 */
export const CallbackApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CallbackApiFp(configuration)
    return {
        /**
         * Mark an upload as failed, or abort a multipart upload. This will free up resources and revert the storage quota.
         * @param {CallbackApiMarkUploadFailedRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        markUploadFailed(requestParameters: CallbackApiMarkUploadFailedRequest, options?: AxiosRequestConfig): AxiosPromise<CallbackMarkUploadFailedResponse> {
            return localVarFp.markUploadFailed(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for markUploadFailed operation in CallbackApi.
 * @export
 * @interface CallbackApiMarkUploadFailedRequest
 */
export type CallbackApiMarkUploadFailedRequest = {
    
    /**
    * 
    * @type {string}
    * @memberof CallbackApiMarkUploadFailed
    */
    readonly xUploadthingVersion: string
    
    /**
    * 
    * @type {string}
    * @memberof CallbackApiMarkUploadFailed
    */
    readonly xUploadthingFePackage?: string
    
    /**
    * 
    * @type {string}
    * @memberof CallbackApiMarkUploadFailed
    */
    readonly xUploadthingBeAdapter?: string
    
} & CallbackMarkUploadFailedRequest

/**
 * CallbackApiGenerated - object-oriented interface
 * @export
 * @class CallbackApiGenerated
 * @extends {BaseAPI}
 */
export class CallbackApiGenerated extends BaseAPI {
    /**
     * Mark an upload as failed, or abort a multipart upload. This will free up resources and revert the storage quota.
     * @param {CallbackApiMarkUploadFailedRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CallbackApiGenerated
     */
    public markUploadFailed(requestParameters: CallbackApiMarkUploadFailedRequest, options?: AxiosRequestConfig) {
        return CallbackApiFp(this.configuration).markUploadFailed(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
