/* tslint:disable */
/* eslint-disable */
/*
UploadThing REST API

UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.

The version of the OpenAPI document: 6.4.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ErrBadRequest } from '../models';
// @ts-ignore
import { ErrInternalServerError } from '../models';
// @ts-ignore
import { ErrUnauthorized } from '../models';
// @ts-ignore
import { MultipartCompleteUploadRequest } from '../models';
// @ts-ignore
import { MultipartCompleteUploadRequestEtagsInner } from '../models';
// @ts-ignore
import { MultipartCompleteUploadResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * MultipartApi - axios parameter creator
 * @export
 */
export const MultipartApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Complete a multipart upload. This will finalize the upload and make the file available for download.
         * @param {string} xUploadthingVersion 
         * @param {string} [xUploadthingFePackage] 
         * @param {string} [xUploadthingBeAdapter] 
         * @param {MultipartCompleteUploadRequest} [multipartCompleteUploadRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        completeUpload: async (xUploadthingVersion: string, xUploadthingFePackage?: string, xUploadthingBeAdapter?: string, multipartCompleteUploadRequest?: MultipartCompleteUploadRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xUploadthingVersion' is not null or undefined
            assertParamExists('completeUpload', 'xUploadthingVersion', xUploadthingVersion)
            const localVarPath = `/completeMultipart`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "x-uploadthing-api-key", keyParamName: "apiKeyAuth", configuration })
            if (xUploadthingVersion != null) {
                localVarHeaderParameter['x-uploadthing-version'] = String(xUploadthingVersion);
            }

            if (xUploadthingFePackage != null) {
                localVarHeaderParameter['x-uploadthing-fe-package'] = String(xUploadthingFePackage);
            }

            if (xUploadthingBeAdapter != null) {
                localVarHeaderParameter['x-uploadthing-be-adapter'] = String(xUploadthingBeAdapter);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: multipartCompleteUploadRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/completeMultipart',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(multipartCompleteUploadRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MultipartApi - functional programming interface
 * @export
 */
export const MultipartApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MultipartApiAxiosParamCreator(configuration)
    return {
        /**
         * Complete a multipart upload. This will finalize the upload and make the file available for download.
         * @param {MultipartApiCompleteUploadRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async completeUpload(requestParameters: MultipartApiCompleteUploadRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MultipartCompleteUploadResponse>> {
            const multipartCompleteUploadRequest: MultipartCompleteUploadRequest = {
                fileKey: requestParameters.fileKey,
                uploadId: requestParameters.uploadId,
                etags: requestParameters.etags
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.completeUpload(requestParameters.xUploadthingVersion, requestParameters.xUploadthingFePackage, requestParameters.xUploadthingBeAdapter, multipartCompleteUploadRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * MultipartApi - factory interface
 * @export
 */
export const MultipartApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MultipartApiFp(configuration)
    return {
        /**
         * Complete a multipart upload. This will finalize the upload and make the file available for download.
         * @param {MultipartApiCompleteUploadRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        completeUpload(requestParameters: MultipartApiCompleteUploadRequest, options?: AxiosRequestConfig): AxiosPromise<MultipartCompleteUploadResponse> {
            return localVarFp.completeUpload(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for completeUpload operation in MultipartApi.
 * @export
 * @interface MultipartApiCompleteUploadRequest
 */
export type MultipartApiCompleteUploadRequest = {
    
    /**
    * 
    * @type {string}
    * @memberof MultipartApiCompleteUpload
    */
    readonly xUploadthingVersion: string
    
    /**
    * 
    * @type {string}
    * @memberof MultipartApiCompleteUpload
    */
    readonly xUploadthingFePackage?: string
    
    /**
    * 
    * @type {string}
    * @memberof MultipartApiCompleteUpload
    */
    readonly xUploadthingBeAdapter?: string
    
} & MultipartCompleteUploadRequest

/**
 * MultipartApiGenerated - object-oriented interface
 * @export
 * @class MultipartApiGenerated
 * @extends {BaseAPI}
 */
export class MultipartApiGenerated extends BaseAPI {
    /**
     * Complete a multipart upload. This will finalize the upload and make the file available for download.
     * @param {MultipartApiCompleteUploadRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MultipartApiGenerated
     */
    public completeUpload(requestParameters: MultipartApiCompleteUploadRequest, options?: AxiosRequestConfig) {
        return MultipartApiFp(this.configuration).completeUpload(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
