/* tslint:disable */
/* eslint-disable */
/*
UploadThing REST API

UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.

The version of the OpenAPI document: 6.4.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ErrBadRequest } from '../models';
// @ts-ignore
import { ErrForbidden } from '../models';
// @ts-ignore
import { ErrInternalServerError } from '../models';
// @ts-ignore
import { ErrUnauthorized } from '../models';
// @ts-ignore
import { RouteConfig } from '../models';
// @ts-ignore
import { UploadRequestPresignedUrlsRequest } from '../models';
// @ts-ignore
import { UploadRequestPresignedUrlsRequestFilesInner } from '../models';
// @ts-ignore
import { UploadRequestPresignedUrlsResponseInner } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * UploadApi - axios parameter creator
 * @export
 */
export const UploadApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Request presigned URLs for file uploads through based on your file router. NOTE: This spec complies with SDK versions ^6.4. Response may vary for older versions.
         * @param {string} xUploadthingVersion 
         * @param {string} [xUploadthingFePackage] 
         * @param {string} [xUploadthingBeAdapter] 
         * @param {UploadRequestPresignedUrlsRequest} [uploadRequestPresignedUrlsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestPresignedUrls: async (xUploadthingVersion: string, xUploadthingFePackage?: string, xUploadthingBeAdapter?: string, uploadRequestPresignedUrlsRequest?: UploadRequestPresignedUrlsRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'xUploadthingVersion' is not null or undefined
            assertParamExists('requestPresignedUrls', 'xUploadthingVersion', xUploadthingVersion)
            const localVarPath = `/prepareUpload`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "x-uploadthing-api-key", keyParamName: "apiKeyAuth", configuration })
            if (xUploadthingVersion != null) {
                localVarHeaderParameter['x-uploadthing-version'] = String(xUploadthingVersion);
            }

            if (xUploadthingFePackage != null) {
                localVarHeaderParameter['x-uploadthing-fe-package'] = String(xUploadthingFePackage);
            }

            if (xUploadthingBeAdapter != null) {
                localVarHeaderParameter['x-uploadthing-be-adapter'] = String(xUploadthingBeAdapter);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: uploadRequestPresignedUrlsRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/prepareUpload',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(uploadRequestPresignedUrlsRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UploadApi - functional programming interface
 * @export
 */
export const UploadApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UploadApiAxiosParamCreator(configuration)
    return {
        /**
         * Request presigned URLs for file uploads through based on your file router. NOTE: This spec complies with SDK versions ^6.4. Response may vary for older versions.
         * @param {UploadApiRequestPresignedUrlsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async requestPresignedUrls(requestParameters: UploadApiRequestPresignedUrlsRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<UploadRequestPresignedUrlsResponseInner>>> {
            const uploadRequestPresignedUrlsRequest: UploadRequestPresignedUrlsRequest = {
                callbackUrl: requestParameters.callbackUrl,
                callbackSlug: requestParameters.callbackSlug,
                files: requestParameters.files,
                routeConfig: requestParameters.routeConfig,
                metadata: requestParameters.metadata
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.requestPresignedUrls(requestParameters.xUploadthingVersion, requestParameters.xUploadthingFePackage, requestParameters.xUploadthingBeAdapter, uploadRequestPresignedUrlsRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * UploadApi - factory interface
 * @export
 */
export const UploadApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UploadApiFp(configuration)
    return {
        /**
         * Request presigned URLs for file uploads through based on your file router. NOTE: This spec complies with SDK versions ^6.4. Response may vary for older versions.
         * @param {UploadApiRequestPresignedUrlsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        requestPresignedUrls(requestParameters: UploadApiRequestPresignedUrlsRequest, options?: AxiosRequestConfig): AxiosPromise<Array<UploadRequestPresignedUrlsResponseInner>> {
            return localVarFp.requestPresignedUrls(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for requestPresignedUrls operation in UploadApi.
 * @export
 * @interface UploadApiRequestPresignedUrlsRequest
 */
export type UploadApiRequestPresignedUrlsRequest = {
    
    /**
    * 
    * @type {string}
    * @memberof UploadApiRequestPresignedUrls
    */
    readonly xUploadthingVersion: string
    
    /**
    * 
    * @type {string}
    * @memberof UploadApiRequestPresignedUrls
    */
    readonly xUploadthingFePackage?: string
    
    /**
    * 
    * @type {string}
    * @memberof UploadApiRequestPresignedUrls
    */
    readonly xUploadthingBeAdapter?: string
    
} & UploadRequestPresignedUrlsRequest

/**
 * UploadApiGenerated - object-oriented interface
 * @export
 * @class UploadApiGenerated
 * @extends {BaseAPI}
 */
export class UploadApiGenerated extends BaseAPI {
    /**
     * Request presigned URLs for file uploads through based on your file router. NOTE: This spec complies with SDK versions ^6.4. Response may vary for older versions.
     * @param {UploadApiRequestPresignedUrlsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UploadApiGenerated
     */
    public requestPresignedUrls(requestParameters: UploadApiRequestPresignedUrlsRequest, options?: AxiosRequestConfig) {
        return UploadApiFp(this.configuration).requestPresignedUrls(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
