/*
UploadThing REST API

UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.

The version of the OpenAPI document: 6.4.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ErrInternalServerError
 */
export interface ErrInternalServerError {
    /**
     * A stringified version of the error
     * @type {string}
     * @memberof ErrInternalServerError
     */
    'error': string;
    /**
     * Additional data related to the error
     * @type {any}
     * @memberof ErrInternalServerError
     */
    'data'?: any | null;
}

