/*
UploadThing REST API

UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.

The version of the OpenAPI document: 6.4.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FileRequestPresignedUrlsRequestFilesInner } from './file-request-presigned-urls-request-files-inner';

/**
 * 
 * @export
 * @interface FileRequestPresignedUrlsRequest
 */
export interface FileRequestPresignedUrlsRequest {
    /**
     * 
     * @type {Array<FileRequestPresignedUrlsRequestFilesInner>}
     * @memberof FileRequestPresignedUrlsRequest
     */
    'files': Array<FileRequestPresignedUrlsRequestFilesInner>;
    /**
     * 
     * @type {string}
     * @memberof FileRequestPresignedUrlsRequest
     */
    'acl'?: FileRequestPresignedUrlsRequestAclEnum;
    /**
     * 
     * @type {any}
     * @memberof FileRequestPresignedUrlsRequest
     */
    'metadata'?: any | null;
    /**
     * 
     * @type {string}
     * @memberof FileRequestPresignedUrlsRequest
     */
    'contentDisposition': FileRequestPresignedUrlsRequestContentDispositionEnum;
}

type FileRequestPresignedUrlsRequestAclEnum = 'public-read' | 'private'
type FileRequestPresignedUrlsRequestContentDispositionEnum = 'inline' | 'attachment'


