/*
UploadThing REST API

UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.

The version of the OpenAPI document: 6.4.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface FileListFilesResponseFilesInner
 */
export interface FileListFilesResponseFilesInner {
    /**
     * 
     * @type {string}
     * @memberof FileListFilesResponseFilesInner
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof FileListFilesResponseFilesInner
     */
    'customId': string | null;
    /**
     * 
     * @type {string}
     * @memberof FileListFilesResponseFilesInner
     */
    'key': string;
    /**
     * 
     * @type {string}
     * @memberof FileListFilesResponseFilesInner
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof FileListFilesResponseFilesInner
     */
    'status': string;
}

