/*
UploadThing REST API

UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.

The version of the OpenAPI document: 6.4.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MultipartUploadURLs
 */
export interface MultipartUploadURLs {
    /**
     * 
     * @type {string}
     * @memberof MultipartUploadURLs
     */
    'key': string;
    /**
     * 
     * @type {string}
     * @memberof MultipartUploadURLs
     */
    'fileName': string;
    /**
     * 
     * @type {string}
     * @memberof MultipartUploadURLs
     */
    'fileType': string;
    /**
     * 
     * @type {string}
     * @memberof MultipartUploadURLs
     */
    'fileUrl': string;
    /**
     * 
     * @type {string}
     * @memberof MultipartUploadURLs
     */
    'ContentDisposition': MultipartUploadURLsContentDispositionEnum;
    /**
     * 
     * @type {string}
     * @memberof MultipartUploadURLs
     */
    'pollingJwt': string;
    /**
     * 
     * @type {string}
     * @memberof MultipartUploadURLs
     */
    'pollingUrl': string;
    /**
     * 
     * @type {string}
     * @memberof MultipartUploadURLs
     */
    'customId': string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof MultipartUploadURLs
     */
    'urls': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof MultipartUploadURLs
     */
    'uploadId': string;
    /**
     * 
     * @type {number}
     * @memberof MultipartUploadURLs
     */
    'chunkSize': number;
    /**
     * 
     * @type {number}
     * @memberof MultipartUploadURLs
     */
    'chunkCount': number;
}

type MultipartUploadURLsContentDispositionEnum = 'inline' | 'attachment'


