/*
UploadThing REST API

UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.

The version of the OpenAPI document: 6.4.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PresignedPostURLs
 */
export interface PresignedPostURLs {
    /**
     * 
     * @type {string}
     * @memberof PresignedPostURLs
     */
    'key': string;
    /**
     * 
     * @type {string}
     * @memberof PresignedPostURLs
     */
    'fileName': string;
    /**
     * 
     * @type {string}
     * @memberof PresignedPostURLs
     */
    'fileType': string;
    /**
     * 
     * @type {string}
     * @memberof PresignedPostURLs
     */
    'fileUrl': string;
    /**
     * 
     * @type {string}
     * @memberof PresignedPostURLs
     */
    'ContentDisposition': PresignedPostURLsContentDispositionEnum;
    /**
     * 
     * @type {string}
     * @memberof PresignedPostURLs
     */
    'pollingJwt': string;
    /**
     * 
     * @type {string}
     * @memberof PresignedPostURLs
     */
    'pollingUrl': string;
    /**
     * 
     * @type {string}
     * @memberof PresignedPostURLs
     */
    'customId': string | null;
    /**
     * 
     * @type {string}
     * @memberof PresignedPostURLs
     */
    'url': string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof PresignedPostURLs
     */
    'fields': { [key: string]: string; };
}

type PresignedPostURLsContentDispositionEnum = 'inline' | 'attachment'


