/*
UploadThing REST API

UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.

The version of the OpenAPI document: 6.4.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RouteConfig } from './route-config';
import { UploadRequestPresignedUrlsRequestFilesInner } from './upload-request-presigned-urls-request-files-inner';

/**
 * 
 * @export
 * @interface UploadRequestPresignedUrlsRequest
 */
export interface UploadRequestPresignedUrlsRequest {
    /**
     * 
     * @type {string}
     * @memberof UploadRequestPresignedUrlsRequest
     */
    'callbackUrl': string;
    /**
     * 
     * @type {string}
     * @memberof UploadRequestPresignedUrlsRequest
     */
    'callbackSlug': string;
    /**
     * 
     * @type {Array<UploadRequestPresignedUrlsRequestFilesInner>}
     * @memberof UploadRequestPresignedUrlsRequest
     */
    'files': Array<UploadRequestPresignedUrlsRequestFilesInner>;
    /**
     * 
     * @type {RouteConfig}
     * @memberof UploadRequestPresignedUrlsRequest
     */
    'routeConfig': RouteConfig;
    /**
     * 
     * @type {any}
     * @memberof UploadRequestPresignedUrlsRequest
     */
    'metadata'?: any | null;
}

